#!/usr/bin/env python3
"""Migrate flat synthetic-text layouts into the model-namespaced layout.

Before:  data/{source}/{kind}/{domain}/...
After:   data/{source}/{kind}/{slug}/{domain}/...

The existing explanations/paraphrases were generated by gpt-5 / gpt-5-mini, so they
are migrated into the `gpt_5_mini` slug by default. Idempotent: directories that are
already a known model slug are left untouched, so re-running is a no-op.

Usage:
    python migrate_to_model_slug.py --dry-run          # preview moves
    python migrate_to_model_slug.py                     # perform moves
    python migrate_to_model_slug.py --sources arxiv --kinds explanations
"""
import argparse
import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))
import utils.utils as utils  # for the known-slug set

# Any directory already named after a known model slug is treated as already-migrated.
KNOWN_SLUGS = set(utils.MODEL_SLUGS.values()) | {"gpt_5_mini", "gpt_5_mini_custom"}


def migrate_kind(source: str, kind: str, slug: str, dry_run: bool) -> int:
    base = REPO_ROOT / "data" / source / kind
    if not base.is_dir():
        return 0
    dest_root = base / slug
    moved = 0
    for entry in sorted(base.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name in KNOWN_SLUGS:
            # already a slug bucket (e.g. gpt_5_mini/, glm/) -> skip
            continue
        target = dest_root / entry.name
        if target.exists():
            print(f"  SKIP  {entry.relative_to(REPO_ROOT)} -> {target.relative_to(REPO_ROOT)} (target exists)")
            continue
        print(f"  MOVE  {entry.relative_to(REPO_ROOT)} -> {target.relative_to(REPO_ROOT)}")
        if not dry_run:
            dest_root.mkdir(parents=True, exist_ok=True)
            shutil.move(str(entry), str(target))
        moved += 1
    return moved


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sources", nargs="+", default=["arxiv", "legal", "medical"])
    parser.add_argument("--kinds", nargs="+", default=["explanations", "paraphrased"])
    parser.add_argument("--slug", default="gpt_5_mini_custom", help="Destination model slug for existing data.")
    parser.add_argument("--dry-run", action="store_true", help="Print planned moves without touching the filesystem.")
    args = parser.parse_args()

    total = 0
    for source in args.sources:
        for kind in args.kinds:
            print(f"[{source}/{kind}] scanning...")
            total += migrate_kind(source, kind, args.slug, args.dry_run)
    verb = "Would move" if args.dry_run else "Moved"
    print(f"\n{verb} {total} domain director{'y' if total == 1 else 'ies'} into '{args.slug}/'.")


if __name__ == "__main__":
    main()
