hf_configuration:
  hf_dataset_name: mybench # change this to your desired dataset name
  private: true # change this to true if you want to make the dataset private. it's true by default.
#   local_saving: true
#   local_dataset_dir: mybench

model_list:
  - model_name: gpt-4.1
    base_url: https://api.openai.com/v1
    api_key: $OPENAI_API_KEY
    max_concurrent_requests: 8

model_roles:
  ingestion:
    - gpt-4.1
  summarization:
    - gpt-4.1
  single_shot_question_generation:
    - gpt-4.1

pipeline:
  #   ingestion:
  #     source_documents_dir: corpus 
  #     output_dir: mybench 
  #     upload_to_hub: true
  #     llm_ingestion: true
  #   upload_ingest_to_hub:
  # summarization:
  #   max_tokens: 500000
  chunking:
    chunking_configuration:
      l_max_tokens: 500000
  single_shot_question_generation:
    run: true
  multi_hop_question_generation:
    run: false
  question_rewriting:
    run: true
  lighteval:
    run: false
  citation_score_filtering:
    run: true
